### PR TITLE
Updated Bat files (Made them more cool)

### PR DESCRIPTION
**Pull request by Darker-Ink**
The Start.bat (Don't mind the error haven't installed my packages yet lmao)
image

### CODE REVIEW

**Comment by 144reasons** [comment]
Hey! Sorry, but I dont really see a use for the reaper ASCII art. If you could remove it, that would be great

**Comment by Darker-Ink** [comment]
> Hey! Sorry, but I dont really see a use for the reaper ASCII art. If you could remove it, that would be great

yep, I did it and added more checks so people don't make issues saying errors trying to start it!

**Comment by 144reasons** [comment]
Hello! I am not too familiar with .bat files, but is it possible to check for a file? If so, that would be a great way to check for the config

**Comment by Darker-Ink** [comment]
> Hello! I am not too familiar with .bat files, but is it possible to check for a file? If so, that would be a great way to check for the config

Indeed you can, I'm working on it rn, the bat files will be a bit messy but it should work!

**Comment by Darker-Ink** [comment]
The only thing it will check though is if there is a config.json file if that is fine!

**Comment by Darker-Ink** [comment]
There you go, Firsttime.bat and start.bat now check for config.json

**Comment by 144reasons** [comment]
This looks good, will merge now

**Pull request merged**
