### PR TITLE
Alot of stuff, too large for the title.

### PR DESCRIPTION
**Pull request by DragonZV**
Mention information, custom prefix, help command, help command fomatting, help command uses client#commands, command category automated to the folder its read in, thus making <command>#type a thing.

### CODE REVIEW

**Comment by 144reasons** [comment]
Hey! I will accept this soon, once I have the chance to look over everything. Thanks for your contribution.

**Comment by 144reasons** [comment]
Just checked, everything looks good, will merge now.

**Comment by DragonZV** [comment]
...wasn't prettier too ugly for you?

**Comment by 144reasons** [comment]
I am going to be reformatting the whole repo

**Pull request merged**
