### PR TITLE
Made Some Issue Templates and updated example command

### PR DESCRIPTION
**Pull request by Darker-Ink**
Made these Issue templates so when someone goes to make a Issue they can pick one of these and get a label auto added to them

### CODE REVIEW

**Comment by 144reasons** [comment]
Hey! Everything looks fine, Ill look into it further tomorrow, as I am too tired to check if it actually works like this!

**Comment by Darker-Ink** [comment]
> Hey! Everything looks fine, Ill look into it further tomorrow, as I am too tired to check if it actually works like this!

Well It would look something like this https://i.ibb.co/7vnx5X5/image.png

**Comment by 144reasons** [comment]
Alright, as I said I will look into it tomorrow, thank you!

**Comment by Darker-Ink** [comment]
oh wait its not conflicting anymore :o

**Comment by 144reasons** [comment]
Hey sorry, I am currently busy working on a branch of the bot where it is supposed to be able to automoderate its own server. I will look into this pr when I get a good amount done. If you are interested in the progress for the automod, I will leave a link to the server down below! (If you plan to invite friends to this server, please use the link below at all times!)

Server: https://discord.gg/MCvVkptYZW

**Comment by 144reasons** [comment]
Hey! This looks all good, will give it a final read in a bit

**Comment by 144reasons** [comment]
Sorry this is a little bit later, but I will be accepting this commit now

**Pull request merged**
