### PR TITLE
Few Things

### PR DESCRIPTION
**Pull request by Darker-Ink**
See I was bored and added this to your bot I guess I always mess code up so ¯\_(ツ)_/¯ you don't need to merge this just wanted to push :3

### CODE REVIEW

**Comment by Darker-Ink** [comment]
By the way May I ask, Is this bot going to use MongoDB.... Or no? Just wondering! :3 Hope you read this and not be like most people I try helping and just send "oh don't make a pr I am working blank blank so it's useless" :(

**Comment by 144reasons** [comment]
Hello! I am currently at school, so I cannot thoroughly review your pull request... Thanks for participating thought!
I have in mind either using keyv or quickmongo, as they are easy to use and understand. Thank you, Samu

**Comment by RobinSchapendonk** [comment]
why are you reading all the files in the help command, when you also can use the client.commands to use the cached commands?

**Review by Robin-Sch — CHANGES_REQUESTED** [review]
Please format your code (using tabs) so it doesn't look that messy. Other than that it (looks) fine.

**Review by Robin-Sch — CHANGES_REQUESTED** [review]
You should use client.commands instead of reading the folders / files every time, although it wouldn't matter on a small bot.

**Review by Robin-Sch — DISMISSED** [review]

**Comment by 144reasons** [comment]
Hello! As Robin suggested, format a little the code, and use client.commands instead of reading every folder as it would make it easier to run when it will have a good amount of commands!

**Review by DragonZV — CHANGES_REQUESTED** [review]
Perhaps you can sort the help command via adding a category property to the command object?

**Comment by 144reasons** [comment]
> Perhaps you can sort the help command via adding a category property to the command object?

This was added already as shown [here](https://samu.sadcomputer.xyz/FFMG)

**Comment by DragonZV** [comment]
You don't seem to understand what I said.

The command itself doesn't have a category property, its just got a temporary property in the help command.

**Comment by DragonZV** [comment]
I dunno how to make changes to a pr so can someone else do it kthx

**Comment by Darker-Ink** [comment]
> You should use client.commands instead of reading the folders / files every time, although it wouldn't matter on a small bot.

Hmmm Do you mean something like this? https://srcb.in/664EhU3K6k Not 100% sure though

**Comment by Darker-Ink** [comment]
There you go I think I formatted It right, I changed the help command to use client.commands (I think thats what you meant) I added a error log thing so people can get errors in a certain channel instead of console (This Might be a bad idea Due to some people using console to check their mistakes but they could do the commands in the error channel and check that way maybe...?) I added a new Color and option to firsttime.js and When testing everything worked for me!

**Comment by 144reasons** [comment]
Hello! I had a look at the code, and everything looked fine, except in one of the commands you imported fs and help two times! Not a problem though... The .bat commands are a great idea, I didn't think of it due to using linux for a few months. Ill change the error channel thing so that if you dont define a channel it will still log in the console. Thank you for contributing to this project, I think your pull is good!

**Comment by DragonZV** [comment]
@somerandomcloud you can use a sh script on linux

**Comment by 144reasons** [comment]
Most users probably dont use linux, but I will add it tomorrow

**Pull request merged**
